version: '3.1'

services:
  app:
    build: .
    command: bash -c "python /app/manage.py migrate --noinput && python /app/manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
      - adminer

  redis:
    build:
      ./redis

  amqp:
    build:
      ./amqp
    environment:
      RABBITMQ_USER: '${RABBITMQ_USER}'
      RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD}'
      RABBITMQ_VHOST: '${RABBITMQ_VHOST}'

  postgres:
    build:
      ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_USER: '${DATABASE_USER}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    build:
      ./adminer
    restart: always
    ports:
      - 9999:8080
    depends_on:
      - postgres

volumes:
  pgdata:
